name: GraSSRep
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - numpy==1.21.2
  - scikit-learn==0.24.2
  - pandas==1.3.3
  - networkx==2.6.3
  - matplotlib==3.4.3
  - wgsim
